[general]
live_config_reload = true
import = ["/Users/field/.config/alacritty/themes/monokai_pro.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
offset = { x = 0, y = 4 }

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
option_as_alt = "OnlyLeft"
padding = { x = 8, y = 8 }
