
includes = [".dotter/mac.toml"]

packages = [
    "zsh",
    "starship",
    "vim",
    "git",
    "alacritty",
    "gitui",
    "helix",
    "zellij",
    "fish",
    "codex",
    "warp",
    "homebrew",
    "zed",
    "aerospace",
]
